export const STATISTICS_TABLE_COLUMNS = [
  { title: 'ТК', dataIndex: 'store', key: 'store' },
  { title: 'Группа', dataIndex: 'productGroup', key: 'productGroup' },
  { title: 'Категория', dataIndex: 'category', key: 'category' },
  { title: 'Подкатегория', dataIndex: 'subcategory', key: 'subcategory' },
  { title: 'Товар', dataIndex: 'productName', key: 'productName' },
  { title: 'Неделя', dataIndex: 'dateRange', key: 'dateRange' },
  { title: 'Факт, руб', dataIndex: 'actualSales', key: 'actualSales' },
  { title: 'Прогноз, руб', dataIndex: 'forecastSales', key: 'forecastSales' },
  { title: 'Разница, руб', dataIndex: 'differenceSales', key: 'differenceSales' },
  { title: 'Факт (кг, шт)', dataIndex: 'actualVolumeAmount', key: 'actualVolumeAmount' },
  { title: 'Разница, (кг, шт)', dataIndex: 'forecastVolumeAmount', key: 'forecastVolumeAmount' },
  { title: 'Факт (кг, шт)', dataIndex: 'differenceVolumeAmount', key: 'differenceVolumeAmount' },
  { title: 'Wape', dataIndex: 'wape', key: 'wape' },
];
